stages:
  - build
  - test
#  - sonar-check
#  - quality-check
  - docker

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  SONAR_PROJECT_KEY: "hohlov.aleksandr.a_simple-messenger"
  SONAR_ORGANIZATION: "hohlov-aleksandr-a"
  SONAR_HOST_URL: "https://sonarcloud.io"
  DOCKER_HUB_REPO: "khkhlv/messenger"
  DOCKER_IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"
  DOCKER_HUB_USER: "khkhlv"

cache:
  key: maven
  paths:
    - .m2/repository

build:
  image: maven:3.8.6-openjdk-18
  stage: build
  tags:
    - messenger
  script:
    - mvn $MAVEN_CLI_OPTS clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 day

test:
  image: maven:3.8.6-openjdk-18
  stage: test
  tags:
    - messenger
  script:
    - mvn $MAVEN_CLI_OPTS test
    - mvn test jacoco:report
  artifacts:
    paths:
      - target/site/jacoco/jacoco.xml
    reports:
      junit: target/surefire-reports/*.xml

sonar-check:
  image: maven:3-openjdk-18
  stage: sonar-check
  tags:
    - messenger
  script:
    - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.tests=src/test/java/ru/khkhlv -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN -Dsonar.sources=src/main/java -Dsonar.tests=src/test/java -Dsonar.java.binaries=target/classes -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
  dependencies:
    - test

check-metrics:
  image: praqma/network-multitool:latest
  stage: quality-check
  tags:
    - messenger
  before_script:
    - apk add --no-cache jq curl bc
  script:
    - |
      echo "Waiting for SonarQube analysis to be available..."
      sleep 10

      PROJECT_KEY="$SONAR_PROJECT_KEY"
      MAX_ATTEMPTS=5
      ATTEMPT=0

      while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
        STATUS=$(curl -s -u "$SONAR_TOKEN": "$SONAR_HOST_URL/api/qualitygates/project_status?projectKey=$PROJECT_KEY" | jq -r '.projectStatus.status')
        echo "$STATUS"
        if [ "$STATUS" = "OK" ]; then
          echo "✅ Quality Gate passed"
          break
        elif [ "$STATUS" = "ERROR" ]; then
          echo "❌ Quality Gate failed"
          exit 1
        fi
        sleep 10
        ATTEMPT=$((ATTEMPT+1))
      done

      if [ $ATTEMPT -eq $MAX_ATTEMPTS ]; then
        echo "⏰ Timeout waiting for Quality Gate"
        exit 1
      fi


# Сборка и пуш Docker-образа
docker:
  stage: docker
  image: docker:24
  tags:
    - messenger
  services:
    - name: docker:24-dind
      alias: docker
  variables:
    DOCKER_TLS_CERTDIR: ""  # отключаем TLS для dind в CI
  before_script:
    - echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKER_HUB_USER" --password-stdin
  script:
    - docker build -t "$DOCKER_HUB_REPO:$DOCKER_IMAGE_TAG" .
    - docker push "$DOCKER_HUB_REPO:$DOCKER_IMAGE_TAG"
    - |
      if [ "$CI_COMMIT_BRANCH" = "main" ]; then
        docker tag "$DOCKER_HUB_REPO:$DOCKER_IMAGE_TAG" "$DOCKER_HUB_REPO:latest"
        docker push "$DOCKER_HUB_REPO:latest"
      fi
  after_script:
    - docker logout